### ISSUE TITLE
Debate topic

### ISSUE THREAD

**Issue by Quasant** [AY2425S1-CS2103-F13-4/tp#102]
## Note final submission is on 12th Nov, roughly 3.5 weeks
I went to double confirm my understanding of how recruitors work. Also found out our software we are creating is called a Applicant Tracking System (ATS), thankfully no good and free CLI version exist. 

Our current model is related to temp/contract staffing. 

There is another model, which is related to direct hire, where we are paid by the company for each successful referral (we do not act as the middleman and handle billing etc). 

With this model, our main gimmick is just matching candidates to jobs, so handling billing cycles is not our responsibility. In other words, all our core features are already implemented, aside from possibly `match job person` which delete the candidate and job at once, and we can now add "undo" or "alias" kind of commands i.e. polish. 

If y'all think this is still too simple, a very simple feature addition is to add a rejection field to the jobs; after interviewing for a job, a candidate may be rejected, so we keep track of that list, so that when we do "screen", we do not include the rejected candidates.

## Things affected if we make this change 

You can view ✅  as things we need to implement if we carry on with the current model and ❌  for things we need to implement with the new model. ❓ is only if we implement certain features.

I could have phrased it as lesser need to do integration, but I wanted to be more specific. This is not an exhaustive list of pros and cons. Also note that some features are shared between the classes, but I just assigned it to one. 

### Job

  - ✅ No need to create a reference of `Person`
  - ✅ When created, no need to check if `CompanyName` exists
  - ✅ When deleted, no need to find its `Company` and remove itself from the reference.
  - ✅ No need for an `attach job person` command, and it's inverse
    - As a bonus, we don't have to care about possible bugs where the `Job` already has someone matched to it, or a `Person` is employed elsewhere 
  - ❌ After a successful match, need to delete the matched `Job` and `Person`
  - ❌ Need to modify the Job
  - ❓ Have to modify `screen`, requires additional check for rejected candidates 
  - ❓ If we allow duplicate roles with same name, same company string, needs a `count` quantity to allow for it
    - Implies need to modify the `match` command 

### Company
- ✅  No need to implement `find contact company` since we no longer do billing stuff
  - Hence, no need to create an `ArrayList<Job>` field
  - As a bonus, no need to implement cascading deletes
  - Related to above, if a `Job` in `ArrayList<Job>` gets deleted, no need to remove the reference of `Job`
- ❌ We can delete things related to this class actually, but a bit sad cause already put in the work   
- ❌ Regression if we delete this class   

### Contact
- ✅ No need to create a reference to `Job`
  - As a bonus, we no longer have to "unemploy" the candidate when it's `Job` gets deleted
- ❓ Needs an attribute `ArrayList<Job>` so that when `this` is deleted, we update all the `Jobs` within that `ArrayList<Job>`
- ❓ There was a nice to have feature, which was the inverse of `screen`, given a candidate, find `Job` suitable for him.

### UI
- 🦖 Okay, honestly I really started thinking hard about this because of the UI considerations, which is slated for implementation within issue #101 

There are probably other stuff but its like 3am now (who knows I might realise this might be a bad idea after I wake up). Feel free to add any pros and cons, or issues that I have missed out. 

I thought about this with the perspective of 
- The grading scheme
- The schedule; are we able to deliver on time?
- Bugs and tests for finals
- The UI, have 3 lists at once, or 3 lists but only 2 can be shown at once. Versus, just a split view.

**Comment by Green-Tea-123** [comment]
I also wanna add that if we make associations between the Job, person, and company, there is no easy way to save and load the associations.
