### ISSUE TITLE
[Alek] `ummatch [non-natural num] [non-natural num]` feedback not specific

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#148]
- I think this is not really a format issue?
- This error message is not specific that the issue is with the index

![image](https://github.com/user-attachments/assets/c5deb805-f7b2-4f64-b396-0cb7a30fda6a)

**Comment by Quasant** [comment]
<img width="952" alt="image" src="https://github.com/user-attachments/assets/5d7f62b0-5ad7-477d-835a-dbbcef1c5315">

<img width="924" alt="image" src="https://github.com/user-attachments/assets/f77fa47e-d66c-415d-80a5-bf636a0949b9">
