### ISSUE TITLE
[Alek] `unmatch` description is not grammatically correct 

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#149]
- I think it should be unmatch "from" instead of "to"

![image](https://github.com/user-attachments/assets/c0df2a21-587b-4ee2-9b32-0abe4aa30a19)

**Comment by Quasant** [comment]
<img width="373" alt="image" src="https://github.com/user-attachments/assets/7e4e3af7-71cd-4226-a326-606ea702f41f">
