### ISSUE TITLE
[General] Bug in scrolling action of the lists in UI

### ISSUE THREAD

**Issue by Green-Tea-123** [AY2425S1-CS2103-F13-4/tp#152]
When I click on a contact/job/company that is currently visible in the list when my scrollbar is all the way at the bottom, then click on any contact/job/company below it in the list order, the list will immediately scroll up about 3/4 the height of a contact/job/company box. This kick up the list also happens if the previously selected item is out of visible range when the list is at the bottom, but the distance moved is much lower.

**Comment by KengHian** [comment]
I managed to replicate this with the original code we fork from, so we inherited the bug from there.

It seem disabling selecting the cell would "fix" this bug, what do you think? Cell selecting no use to us anyways.
