### ISSUE TITLE
[Ben] `add job` allows empty description

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#179]
- not sure if this is intended
- but it d/ is mandatory, does not make sense to have an empty description right
![image](https://github.com/user-attachments/assets/6c122b86-234b-4646-a55b-ff80685ed4fb)

**Comment by Quasant** [comment]
<img width="389" alt="image" src="https://github.com/user-attachments/assets/3569c3c2-bc14-4821-8c8c-fc818002ffb4">
