### ISSUE TITLE
[Ben] `add job` fail silently when a large number is provide as salary

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#181]
-  I think we can state restriction of the size of salary number in usage message
- handle this gracefully by handling the exception and provide a meaningful feedback to the user

![image](https://github.com/user-attachments/assets/b8201f55-3120-44d7-a553-bde0a0b059a0)

![image](https://github.com/user-attachments/assets/dfee88af-d810-4e41-a517-1413b15cd39a)

**Comment by Quasant** [comment]
<img width="462" alt="image" src="https://github.com/user-attachments/assets/1358228e-74a9-43ac-a43a-dc543852d164">
