### ISSUE TITLE
[Ben] `add job` invalid feedback message not specific when a negative salary if provided

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#182]
![image](https://github.com/user-attachments/assets/b6303d2d-5b85-4c6b-8240-2f7024106384)

**Comment by Quasant** [comment]
<img width="742" alt="image" src="https://github.com/user-attachments/assets/f90bba46-7f85-4fb5-b36d-f37bfaef55f6">
