### ISSUE TITLE
[Ben] `add job` usage message not specific

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#183]
- Unsure what is the time period of the salary, is it per month? Maybe we can just specify one and stick to it for now (add allowing different time period as future features)
- What does square bracket mean? Can I specify multiple entries for a specific prefix? See below on how `add contact` address this

![image](https://github.com/user-attachments/assets/3b766e79-47c0-48c0-9394-276e2d8301f5)

![image](https://github.com/user-attachments/assets/2e310230-6756-4491-94ea-67e776744770)

**Comment by Quasant** [comment]
<img width="742" alt="image" src="https://github.com/user-attachments/assets/e378039d-ec5f-43da-8cbe-3aa40c35134f">

and for the job card

<img width="274" alt="image" src="https://github.com/user-attachments/assets/51ceaf81-4bc5-4184-91ca-4084aba58636">
