### ISSUE TITLE
[Ben] `add job` repeated requirements got merged as one

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#184]
- I understand that is how tags are implemented, but without feedback this might seems as unpredictable behavior, since user might not know requirement is implemented via sets
- Perhaps have a feedback indicating that duplicated tags are detected and has been merged, or indicate that clearly in the usage message, or both
- Can close it if you think this is not an issue

![image](https://github.com/user-attachments/assets/9ef0d682-eee5-45b7-890c-0c07805ea0c5)

**Comment by Green-Tea-123** [comment]
I think we should keep this actually, since repeated requirements aren't exactly desired. We can specify that repeated tags/skills will always resolve to only unique skills/tags in the address book.

**Comment by Quasant** [comment]
Dropping this issue, while it can be implemented, simply writing within the user guide should be sufficient.
