### ISSUE TITLE
[Ben] `delete job` gave invalid format error when large index is provided 

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#185]
- Perhaps not the most fitting error message, since I did provide a positive integer

![image](https://github.com/user-attachments/assets/4883f918-6f5c-4f62-8b1e-f46e41e52623)

**Comment by Quasant** [comment]
<img width="921" alt="image" src="https://github.com/user-attachments/assets/b89ac117-0116-449d-857c-5a6acb68636a">
