### ISSUE TITLE
[Ben] `load JSON Person match` Person loaded non-existing job after modifying JSON file

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#187]
![image](https://github.com/user-attachments/assets/7321a384-1377-4b21-b4cd-d974671bceb0)

**Comment by Quasant** [comment]
<img width="946" alt="image" src="https://github.com/user-attachments/assets/0082c742-209c-406c-a27f-7d2d4edd04bd">
