### ISSUE TITLE
[Ben] `load JSON Person match` didn't fail gracefully with JSON is "corrupted"

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#188]
- Probably due to the missing "::"

![image](https://github.com/user-attachments/assets/61bbeffd-2d1f-4b4c-b787-40ff6e8f4819)
![image](https://github.com/user-attachments/assets/597f93e9-cee2-4bca-b591-2fdb7c7513bd)

**Comment by Quasant** [comment]
Resolved via a check within toModelType().

![image](https://github.com/user-attachments/assets/272829c1-da09-456b-a618-9aeb23197349)
