### ISSUE TITLE
[JunBoon] `jobCompany Integration` app fail to start when JSON is modified such that job has a non-existing company

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#189]
- Perhaps a more graceful way is the assume that JSON file is corrupted and start with a fresh JSON file?

![image](https://github.com/user-attachments/assets/c9b0b684-d96f-480a-b2e1-b193bf07f0ef)

**Comment by Green-Tea-123** [comment]
Alright, I can just catch the CompanyNotFound Exception when loading the address book and return a fresh one if the address book was corrupted.
