### ISSUE TITLE
[JunBoon] Phone number should have a limit on length

### ISSUE THREAD

**Issue by Quasant** [AY2425S1-CS2103-F13-4/tp#192]
Currently there is a minimum length of 3 digits, however there is no limit on how long it can be. Granted, we can simply say that the user is responsible for their own input. 

<img width="374" alt="image" src="https://github.com/user-attachments/assets/39563e21-0d37-4b1c-916a-718f31d75959">

**Comment by Green-Tea-123** [comment]
I'll fix this, probably gonna restrict the max length to 15 digits like in our feature specs
