### ISSUE TITLE
[General/JunBoon] Messing with JSON in general results in the UI not loading up the lists

### ISSUE THREAD

**Issue by Quasant** [AY2425S1-CS2103-F13-4/tp#195]
While working on fixing issue #179, I encountered a bug when I implemented validation, in that the sampleData used to load up the app is of an invalid form. I had a thought and realized that (most likely) for all fields, playing around with the JSON would result in an error. 

In JunBoon's case, if I add a unicode character it is an invalid `Name`. 

<img width="986" alt="image" src="https://github.com/user-attachments/assets/5711e6fc-f833-487a-b0b2-da5dfdc3b50d">

**Comment by Green-Tea-123** [comment]
There was another issue that was of the same nature. I will on it.
