### ISSUE TITLE
[Zewei] Incorrect error message when deleting company

### ISSUE THREAD

**Issue by Quasant** [AY2425S1-CS2103-F13-4/tp#196]
Seems to be a common issue across multiple commands, but essentially it returns an invalid index message when the `ENTITY WORD` is missing.

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/4cdd2a96-76b9-4f31-89e4-42dd2bfbf158">

**Comment by KengHian** [comment]
Fixed.
