### ISSUE TITLE
[JunBoon] Add company only checks company name for duplicates

### ISSUE THREAD

**Issue by wassilililily** [AY2425S1-CS2103-F13-4/tp#205]
<img width="742" alt="Screenshot 2024-11-02 at 12 42 35" src="https://github.com/user-attachments/assets/68936ed4-a1d9-465b-ab01-860073e07d96">

Maybe we can add more checks for duplicate companies

**Comment by Green-Tea-123** [comment]
I'll make the duplicate check case-insensitive
