### ISSUE TITLE
[Ben] Add job invalid requirements can give clearer instructions

### ISSUE THREAD

**Issue by wassilililily** [AY2425S1-CS2103-F13-4/tp#206]
<img width="742" alt="Screenshot 2024-11-02 at 12 58 01" src="https://github.com/user-attachments/assets/084550ce-2aba-4e46-bcb2-2b91a45b7a3a">

Maybe can say something about having no whitespace in the requirements

**Comment by Green-Tea-123** [comment]
This is outdated, tags can have whitespace now.

**Comment by KengHian** [comment]
Resolved by Jun Boon.
