### ISSUE TITLE
[ZeWei] `view` usage message does not specify "company" is needed, it also does not validate if the entity is valid

### ISSUE THREAD

**Issue by KengHian** [AY2425S1-CS2103-F13-4/tp#214]
- `view contact 1` works the same as `view company 1`

**Comment by wassilililily** [comment]
Are you able to provide screenshot to this? I am unable to reproduce this bug.

**Comment by KengHian** [comment]
![image](https://github.com/user-attachments/assets/5d8a59b0-2dc1-4898-b2c1-f33555c37e1f)

**Comment by KengHian** [comment]
Fixed somewhere.
