### ISSUE TITLE
[PE-D][Tester E] Cannot use just keyboard to close Help without risking closing the wrong things

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#262]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/231a2fa3-f39d-48ea-97d3-95b33d8f32c3.png)

While Alt+F4 works to close the Help Window, it runs the risk of closing something else entirely.
And now I have to use the mouse to close it myself.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: starchypotatocode/ped#2

**Comment by Quasant** [comment]
I don't use windows and I don't have a shortcut to close that so can't comment on this.

**Comment by KengHian** [comment]
Alt/Ctrl+F4 will close a window/app in Windows. I am not sure how to address this issue, since even if the user use mouse, there is also a risk for them to close something entirely.

**Comment by KengHian** [comment]
Reject? 
- [ ] Alek
- [ ] Ben
- [ ] Ze Wei
- [ ] Jun Boon
- [ ] Keng Hian

**Comment by Quasant** [comment]
Rejected, majority vote + low severity (a user will not encounter this problem often) + frankly I don't feel like wasting an enhancement on this.
