### ISSUE TITLE
[PE-D][Tester E] Weird ordering of UI / message

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#272]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/9fb746c9-e502-42d0-b729-2e932337eff8.png)

Probably too nitpicky, but why is the ordering contact > company > job > all
when the UI ordering is Contacts > Jobs > Companies?

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: starchypotatocode/ped#5

**Comment by Quasant** [comment]
It is a valid remark ... but imho if there was a severity lower than VeryLow, I would put it here.

**Comment by Quasant** [comment]
I moved to rejected, as while a valid feature flaw, it is nit-picky and also we cannot fix it or it will violate feature freeze. 

Reason why violate:
The fix to this is not because the behaviour is strictly incorrect, but it can be better.
