### ISSUE TITLE
[PE-D][Tester C] Find does not work as described in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#273]
![Screenshot 2024-11-08 at 4.21.03 PM.png](https://raw.githubusercontent.com/jinhanjinhan/ped/main/files/70f81d5d-db6c-4286-8afc-71fb8225915a.png)

Find does not work as described in UG, should be "find contact..." i assume? 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jinhanjinhan/ped#3

**Comment by Quasant** [comment]
Again can go both ways.

Anyways, update UG.  

I actually reported the `Only full words will be matched` as a bug for my assigned PE-d, so if we want to adhere to that, it is a functionality bug.
