### ISSUE TITLE
[PE-D][Tester C] Use case not labelled properly

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#288]
Use case not labelled properly, a cosmetic issue but it also hinders with the reading from a user's perspective. Perhaps can add more spacing and remove the bold on MSS and extensions. Or perhaps can use a numbering system like Use Case 1, Use Case 2, etc…

![Screenshot 2024-11-08 at 4.33.38 PM.png](https://raw.githubusercontent.com/jinhanjinhan/ped/main/files/d753c5c8-fa20-4a84-ba4b-13f3345f815f.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jinhanjinhan/ped#8

**Comment by Quasant** [comment]
Related to 
- #335

**Comment by Green-Tea-123** [comment]
Wait I actually think this is on purpose, this was from the previous DG

**Comment by Quasant** [comment]
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/b14b2af0-28ac-43d6-bc67-425c6f810ea8">
