### ISSUE TITLE
[PE-D][Tester E] Lack of whitespace processing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#289]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/7c820f22-8536-4875-a2cb-73defd2dadcd.png)

Entry 12 should have its repeated whitespace trimmed off

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: starchypotatocode/ped#9

**Comment by KengHian** [comment]
I do not see the point of preventing user on using 2 spaces in the middle of their text if they wish to, could be consider overzealous input validation.

**Comment by KengHian** [comment]
Reject? 
- [ ] Alek
- [ ] Ben
- [ ] Ze Wei
- [ ] Jun Boon
- [x] Keng Hian
