### ISSUE TITLE
[PE-D][Tester C] Screen job command similar to find command, should standardise them

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#295]
Screen job seems similar to the find command, find command filters based on the name of the contacts, whereas screen job command filters based on the role of the contacts. I think it would be better if this feature is implemented as an extension of find command, such as maybe “find n/…” to find by name, and “find r/…” to find by the user’s role. 
![Screenshot 2024-11-08 at 4.39.23 PM.png](https://raw.githubusercontent.com/jinhanjinhan/ped/main/files/c9cdefee-d37d-4688-98aa-9b9820638292.png)

Implementing them as two separate commands make it hard for the user to remember the syntax, and also makes it hard for future extensions to occur. What if you were required to implement a feature to filter by the skills of the contacts?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jinhanjinhan/ped#11

**Comment by Quasant** [comment]
Good points raised. +1  

Proposed to have this be covered under planned enhancements - screen job accepts alternative parameters. 

As an aside, I put severity.High not because this issue itself is very severe but more of for us to discuss and align our understanding of `find` and `screen`

**Comment by KengHian** [comment]
@Quasant you already added this to Planned enhancement right? If so we can close this issue. 

Also, find and screen are meant to be different. If the screen algo is more complex, user do not need to refer to the job info and type out one by one. 

Currently it only seem this way because screen only check with role.
