### ISSUE TITLE
[PE-D][Tester B] Command format for find stated in UG is not applicable in the application

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#299]
Command format for UG states that these parameters are required for find:
![image.png](https://raw.githubusercontent.com/gohsl99/ped/main/files/f1f1bc29-2061-48c9-9aa8-cbbb6140cd8a.png)

But the application requires a different command format:
![image.png](https://raw.githubusercontent.com/gohsl99/ped/main/files/47efad6c-6c2a-45fb-8c8e-b65d587f8f93.png)

Command to reproduce: find

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: gohsl99/ped#6

**Comment by Quasant** [comment]
Related issues
- #297 and issues linked there
