### ISSUE TITLE
[PE-D][Tester C] List features seem abit redundant

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#315]
I don’t really see the need for 3 separate features `list job, list company, list contact` to list these three separately, as when I am using it, all I have to do is to use `list all` command, and I can see everything again. Instead of having these 3 features, I thought it would be better its these 3 features could do something like for example, `list contact` lists all existing contacts that are not matched yet so that it would be better for me as a recruiter to match them a job. Same goes for `list company` and `list job`.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jinhanjinhan/ped#20

**Comment by Quasant** [comment]
I am not sure if I want to use an enhancement on this. 

To discuss if there are possible cases where a user might not want to list all.

**Comment by Green-Tea-123** [comment]
Yeah, and having more lists is not exactly harmful to the functionality of the app

**Comment by KengHian** [comment]
> lists all existing contacts that are not matched yet

This is a valid enhancement, we should include that.
