### ISSUE TITLE
[PE-D][Tester E] Find method should accept numbers because name accepts numbers

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#316]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/50e42a1c-839f-4f10-817c-e06a68de02a4.png)

What if I named the guy John 1 John 2 and needed to find John 2?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: starchypotatocode/ped#15

**Comment by Quasant** [comment]
Tested it, `find contact 33` works, however there were UG issues raised. 

If anyone disagrees with `Reject`, change the label to `Discuss`.

**Comment by KengHian** [comment]
Reject?
- [ ] Alek
- [ ] Ben
- [ ] Ze Wei
- [ ] Jun Boon
- [ ] Keng Hian

**Comment by KengHian** [comment]
I do not think we should reject this issue, sine the tester is following our UG command, it is natural for them to assume this command should be valid, we should classify this issue as a valid Documentation bug.

**Comment by Quasant** [comment]
I see, regardless, this is fixed with the pr #260.
