### ISSUE TITLE
[PE-D][Tester B] Inconsistent parameters for unmatch

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#317]
In UG, the parameters for unmatch is show as:

![image.png](https://raw.githubusercontent.com/gohsl99/ped/main/files/cbf88c49-685f-4c3b-8740-35fa936c0924.png)

However it is like this in application (with the extra "<>"):

![image.png](https://raw.githubusercontent.com/gohsl99/ped/main/files/c7979936-8927-4e10-82d4-9d0c901dffd3.png)

Command to reproduce: unmatch.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: gohsl99/ped#9

**Comment by KengHian** [comment]
Link to 

- https://github.com/AY2425S1-CS2103-F13-4/tp/issues/349

Closing duplicate issue.
