### ISSUE TITLE
[PE-D][Tester D] Matching jobs to persons

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#318]
If I have 2 jobs with the same name but different salary and description, I am unable to figure out which job the person is linked to.
![Screenshot 2024-11-08 at 5.02.19 PM.png](https://raw.githubusercontent.com/karthickkc/ped/main/files/29879d0d-943f-408c-99c2-f6452c7360b9.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: karthickkc/ped#4

**Comment by Quasant** [comment]
This seems related to 
- #306 and issues linked within that

In the first place, it should not be possible to have jobs with the same name.

**Comment by KengHian** [comment]
They are not the same name, but I get what the tester is trying to say. 

Since there isn't any other way to see the match, I think this is a functionality bug that can be fixed by wrap text.

**Comment by Quasant** [comment]
Duplicate issue.
