### ISSUE TITLE
[PE-D][Tester E] Incorrect UG and error message for edit

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#320]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/285f7ccb-1ad7-4c47-b39a-0588d393fa4d.png)

1) UG does not reflect actual commands
2) [contact] makes me think that it is optional as listed elsewhere
3) why have additional typing if you don't have edit company or equivalent?

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: starchypotatocode/ped#16

**Comment by Quasant** [comment]
This is actually related to 2 issues.

- #314 
- #286 and related issues

**Comment by Quasant** [comment]
1st issue has been fixed, mostly 2nd and 3rd issue awaiting fix

**Comment by Quasant** [comment]
Now only left the the 2nd issue

**Comment by KengHian** [comment]
I think the second issue is probably a functionality bug, it is strictly false to use the optional bracket. I think we can change the code for this.

**Comment by KengHian** [comment]
Second issue link to 

-  https://github.com/AY2425S1-CS2103-F13-4/tp/issues/360

Closing duplicate issue.
