### ISSUE TITLE
[PE-D][Tester E] Inaccurate error message for skill

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#322]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/9ffcceb1-afe6-47e5-8a51-1edc7ce637cd.png)

current wording implies 0 0 as skill is not possible, which is false

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: starchypotatocode/ped#17

**Comment by Quasant** [comment]
Linked to 
- #322 (allows spaces)
