### ISSUE TITLE
[PE-D][Tester E] Incomplete UG Documentation for Find

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#325]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/58f96aee-d2fe-4833-b6cf-d6a4bb8cfbad.png)

Same issue as edit iirc

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: starchypotatocode/ped#18

**Comment by Quasant** [comment]
Linked to 

- #294 and related

**Comment by Quasant** [comment]
Linked to #260, just that this went under radar (#294 and this have a cyclical link)
