### ISSUE TITLE
[PE-D][Tester B] Outdated UML diagram in DG for Person

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#328]
Updated UML for Person should be similar to this (page 10):

![image.png](https://raw.githubusercontent.com/gohsl99/ped/main/files/dc9bcf61-7ecc-4d3c-a50a-9ca34b9609cb.png)

But the next UML (in page 11) is not updated:

![image.png](https://raw.githubusercontent.com/gohsl99/ped/main/files/fd752c48-84f9-410e-b890-9a49e8daa84b.png)

Good to keep them consistent.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: gohsl99/ped#11

**Comment by Quasant** [comment]
#283

**Comment by KengHian** [comment]
Closing this issue, fixed with https://github.com/AY2425S1-CS2103-F13-4/tp/pull/368.
