### ISSUE TITLE
[PE-D][Tester C] Screen job does not work as specified in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#330]
`screen job` feature does not work as specified, UG says it filters the contact with role matching the name, so by default, I would assume it is full string matching. But however, when I do `screen job 1`, it shows all contacts that partially match the job name string. 
![Screenshot 2024-11-08 at 5.14.20 PM.png](https://raw.githubusercontent.com/jinhanjinhan/ped/main/files/30605b16-7690-42d6-9492-0b722fdd4b77.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jinhanjinhan/ped#22

**Comment by Quasant** [comment]
Could go both ways, personally I think its a documentation bug but if we actually did intend to do a strict matching, then it is a functionality bug.

**Comment by KengHian** [comment]
This is a documentation bug. Strict matching would make the job matching pretty hard, and it would probably be a feature flaw.
