### ISSUE TITLE
[PE-D][Tester C] Screen job functionality is limited

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#333]
Screen job feature is limited in functionality, so it is less useful than it can be. When I have a contact with the title company ”Software Engineering Head”, and I do screen job 1, it should show this contact as well since this contact should qualify as a valid software engineering manager, but however, this contact does not show. 

Perhaps you should implement it like how find is implemented, like contacts matching at least one keyword will be returned.

<i><video controls><source src="https://raw.githubusercontent.com/jinhanjinhan/ped/main/files/64caa106-15bd-4b10-963d-56ddf392e8aa.mov" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/jinhanjinhan/ped/main/files/64caa106-15bd-4b10-963d-56ddf392e8aa.mov</i>

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jinhanjinhan/ped#23

**Comment by Quasant** [comment]
There was a related issue which I cannot find for now, but it has to do with screening via other parameters by salary, skills etc. to differentiate from the find command. 

I dumped a lot of labels here to discuss whether this is a feature flaw, or a functionality bug.

**Comment by KengHian** [comment]
I think this is a separate matter, but I do not think this is a bug/feature flaw. 

If a contact is applying for a specific role such as software engineering head, why would we assume that he want to be match to software engineer manger? Whereas if you are applying for a general job such as software engineer, then it make sense to show more options.
