### ISSUE TITLE
[PE-D][Tester A] Billing date

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#336]
![Screenshot 2024-11-08 at 5.14.29 PM.png](https://raw.githubusercontent.com/WuJinhan1/ped/main/files/1eea6403-9753-4490-af2c-297e8075b4cc.png)
The billing date should be able to be above 28 since a billing date can vary from 28–31 days

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: WuJinhan1/ped#14

**Comment by Quasant** [comment]
Related to 
- #266

**Comment by KengHian** [comment]
Closing duplicate issue
