### ISSUE TITLE
[PE-D][Tester E] Inconsistent error message (Screen)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#348]
screen: Filters and displays entities matching the specified criteria. 

Parameters:
- job <INDEX>: Screens and lists contacts that fit the specified job.

Example:
screen job 1

why is this so long unlike the others?

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: starchypotatocode/ped#26

**Comment by Quasant** [comment]
Is this considered a functionalityBug?

**Comment by KengHian** [comment]
Not a bug at all, everything is strictly correct. I don think this is a cosmetic bug as well, just more of a standazing thing, which we can't fix i think.
