### ISSUE TITLE
[PE-D][Tester E] Incorrect UG documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-4/tp#350]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/f278818f-f4e6-4a37-9442-6eaeff70003b.png)

Low as it's super obvious if you try and follow the UG

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: starchypotatocode/ped#28

**Comment by Quasant** [comment]
- #280 related issue
