### ISSUE TITLE
[PE-D][Tester E] Random weird whitespace in pdf: error in layout or artifact of conversion?

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#352]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/6be81fda-4a79-4f51-b83e-bc6ea0ed9b36.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: starchypotatocode/ped#29

**Comment by KengHian** [comment]
I think we can reject this issue, I think just formatting to prevent the architecture diagram to be cut in half?

**Comment by KengHian** [comment]
Reject? 
- [ ] Alek
- [ ] Ben
- [ ] Ze Wei
- [ ] Jun Boon
- [x] Keng Hian
