### ISSUE TITLE
[PE-D][Tester E] Information Overload in the DG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-4/tp#355]
![image.png](https://raw.githubusercontent.com/starchypotatocode/ped/main/files/ffa01eb3-7949-40bb-aa73-3373c03e2dab.png)

Would it be possible to split this into more diagram? This is too much information to help check for errors at this stage..

Also, the 'more OOP model' is liekly out of date

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: starchypotatocode/ped#32

**Comment by KengHian** [comment]
Link to https://github.com/AY2425S1-CS2103-F13-4/tp/issues/283.
